# Generated by Django 4.1.10 on 2024-03-24 19:11

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "movielens_id",
                    models.BigAutoField(
                        db_index=True, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "genres",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("Action", "Action"),
                                ("Adventure", "Adventure"),
                                ("Animation", "Animation"),
                                ("Children's", "Childrens"),
                                ("Comedy", "Comedy"),
                                ("Crime", "Crime"),
                                ("Documentary", "Documentary"),
                                ("Drama", "Drama"),
                                ("Fantasy", "Fantasy"),
                                ("Film-Noir", "Film Noir"),
                                ("Horror", "Horror"),
                                ("Musical", "Musical"),
                                ("Mystery", "Mystery"),
                                ("Romance", "Romance"),
                                ("Sci-Fi", "Sci Fi"),
                                ("Thriller", "Thriller"),
                                ("War", "War"),
                                ("Western", "Western"),
                                ("(no genres listed)", "No Genre Listed"),
                            ],
                            max_length=20,
                        ),
                        size=None,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("movielens_user_id", models.IntegerField()),
                ("text", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="movies.movie",
                    ),
                ),
            ],
            options={
                "unique_together": {("movielens_user_id", "movie", "text")},
            },
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("movielens_user_id", models.IntegerField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="movies.movie"
                    ),
                ),
            ],
            options={
                "unique_together": {("movielens_user_id", "movie")},
            },
        ),
    ]
